### ISSUE TITLE
Strange behaviour when subsetting and coercing to vector

### ISSUE THREAD

**Issue by kdkorthauer** [Bioconductor/DelayedArray#23]
Hi, 

I noticed some strange behavior in the devel version of DelayedArray (0.7.19). When subsetting and coercing a DelayedMatrix to a vector, the output is twice the length I'd expect, and doesn't contain the correct elements.

Here is a minimal example:

```{r}
require(DelayedArray)
m <- DelayedArray(matrix(0:8, ncol = 3))
m[m>0]
 [1] 1 2 0 1 2 0 1 2 0 0 1 1 1 2 2 2
```

This doesn't happen in the release version of DelayedArray (0.6.1). Here, the example gives the expected output:

```{r}
require(DelayedArray)
m <- DelayedArray(matrix(0:8, ncol = 3))
m[m>0]
[1] 1 2 3 4 5 6 7 8
```

**Comment by hpages** [comment]
Thanks @kdkorthauer for the report!

[This commit](https://github.com/Bioconductor/DelayedArray/commit/59e08345689127ce32757c7f13b358963ae6dbac) should fixed it. The fix is in DelayedArray 0.7.24 and will become available via `BiocManager::install("DelayedArray")` in a couple of days, or immediately with `BiocManager::install("Bioconductor/DelayedArray")`.

H.
