### ISSUE TITLE
Implementing crossprod and dual-DA %*%

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/DelayedArray#33]
I recently needed `crossprod` for DA objects, as well as a `%*%` that would accept two DAs. I've put the code I've used [here](https://gist.github.com/LTLA/7cf5d6231a9616084803429348760760), in the hope that it may help development of the methods within the _DelayedArray_ package itself. Both functions are parallelized by splitting the input DA into blocks that contain all columns (for `crossprod`) or all rows (for `%*%`), and then distributing each block to a separate worker for calculations. 

One major difficulty is that this strategy does not respect the maximum block size defined by `setAutoBlockSize`. Rather, the size of the blocks is inversely proportional to the number of cores. Each block is fully realized in memory during processing, so the core-based definition of the block size may exceed memory limits for a very large input matrix. While I'm aware of `colGrid` and `rowGrid`, these may not define blocks with sufficient granularity to allow distribution across the specified number of workers. Someone who sets `setAutoBlockSize` to a very large value - ostensibly to improve performance - would end up having very few blocks from `colGrid` or `rowGrid` to process independently.

Tagging @kasperdanielhansen who may also have some code lying around to do this.

**Comment by hpages** [comment]
Thanks Aaron. I'll try to take a look at this in the next couple of weeks. Improving support for matrix multiplication in DelayedArray has been on my list for a while but I first had to spend some time (which turned out to be months) improving a few things about block-processing (in particular support blocks of arbitrary geometry) before I could support matrix multiplication between 2 DelayedArray objects.

**Comment by LTLA** [comment]
In the meantime, I've had a deep think about some of the issues involved:

https://docs.google.com/document/d/1ONjkv6F0sMsfEIR1DzxCxmn8DrixFAvu5-7_j_38c5c/edit?usp=sharing

Perhaps this may be helpful for you when you get around to implementing these functions.

**Comment by hpages** [comment]
Summarizing here the discussion we started on the Bioc-community slack in the delayed_array channel about the new `%*%` methods introduced by your patch: https://github.com/Bioconductor/DelayedArray/pull/38

One problem with this change is that matrix multiplication involving DelayedMatrix objects now returns an ordinary matrix instead of a DelayedMatrix object.

For example in the following example (from ``?`DelayedArray-utils` ``), `P` should be returned as an HDF5Array object:
```
library(HDF5Array)
toy_h5 <- system.file("extdata", "toy.h5", package="HDF5Array")
M1 <- HDF5Array(toy_h5, "M1")
m <- matrix(runif(50000), ncol=nrow(M1))
setRealizationBackend("HDF5Array")
P <- m %*% M1
class(P)  # ordinary matrix (should be HDF5Array)
```

The patch adds support for multiplication of 2 DelayedMatrix objects. In this case too the result should be a DelayedMatrix object. Right now it's not:
```
m1 <- matrix(1:240, ncol=8)
M1 <- writeHDF5Array(m1, chunkdim=c(1, 8))
m2 <- matrix(10001:10120, nrow=8)
M2 <- writeHDF5Array(m2, chunkdim=c(8, 1))
setRealizationBackend("HDF5Array")
setAutoBlockSize(100)
P <- M1 %*% M2
class(P)  # ordinary matrix (should be HDF5Array or something "close" to it, see below)
```
Here is how this multiplication is currently performed (removing parallelization from the equation from now by using `lapply()` instead of `bpiterate()`):
```
scheme_out <- DelayedArray:::.dispatch_mult(M1, M2, bpnworkers(bpparam()))
# scheme_out$choice is "x"
chosen_grids <- scheme_out$grid
out0 <- lapply(seq_along(chosen_grids$x),
    function(b) {
        x_viewport <- chosen_grids$x[[b]]
        x_block <- read_block(M1, x_viewport)
        x_block %*% M2  # this produces an ordinary matrix
    }
)
P0 <- do.call(rbind, out0)
```
Problem is that at each iteration an ordinary matrix is produced. But what we should do instead is produce an HDF5Array object. We can do this by doing `DelayedArray:::.BLOCK_mult_by_left_matrix(x_block, M2)` instead of `x_block %*% M2`:
```
out1 <- lapply(seq_along(chosen_grids$x),
    function(b) {
        x_viewport <- chosen_grids$x[[b]]
        x_block <- read_block(M1, x_viewport)
        DelayedArray:::.BLOCK_mult_by_left_matrix(x_block, M2)
    }
)
P1 <- do.call(rbind, out1)
```
`P1` is a DelayedArray object that is made of 10 HDF5Array objects bound together:
```
> showtree(P1)
30x15 integer: DelayedMatrix object
└─ 30x15 integer: Abind (along=1)
   ├─ 3x15 integer: [seed] HDF5ArraySeed object
   ├─ 3x15 integer: [seed] HDF5ArraySeed object
   ├─ 3x15 integer: [seed] HDF5ArraySeed object
   ├─ 3x15 integer: [seed] HDF5ArraySeed object
   ├─ 3x15 integer: [seed] HDF5ArraySeed object
   ├─ 3x15 integer: [seed] HDF5ArraySeed object
   ├─ 3x15 integer: [seed] HDF5ArraySeed object
   ├─ 3x15 integer: [seed] HDF5ArraySeed object
   ├─ 3x15 integer: [seed] HDF5ArraySeed object
   └─ 3x15 integer: [seed] HDF5ArraySeed object
```
This binding is delayed. If we really wanted the final result as an HDF5Array object we would need to realize the binding:
```
P2 <- realize(P1)
```
However, this extra step can be costly and cannot be parallelized (HDF5 does not support concurrent writing) so `%*%` should not do it. Anyway, for most use cases, this step is not needed. The user should be able to work directly with `P1` and not be significantly impacted by the fact that `P1` carries a delayed `rbind` operation. The man page for `%*%` will need to explain/discuss this.

To bring back parallelization just replace `lapply` with `bplapply` in the above code. Et voila ! No need to use `bpiterate`.

Note that this implementation of a parallel `%*%` uses 2 level of looping: an outer loop using `bplapply` and an inner loop just using a `for` loop (this loop is implemented inside `DelayedArray:::.BLOCK_mult_by_left_matrix`). Each loop uses its own grid. Ideally the outer loop should use a very coarse grid with 1 block per worker and where blocks are made of adjacent rows or columns. There is no reason for the outer loop to use `read_block()`, it should subset instead (which is delayed so that doesn't load anything in memory). The advantage of doing this is that there is no need for the outer grid to honor the user-specified "max block size". OTOH the inner grid should use a finer grid that honors the user-specified "max block size". For example if `x` is 75000x55000 and `y` is 55000x25000 and we have 10 workers, we could split `x` in 10 sub-matrices of 7500x55000 each (outer grid). Then worker #1 would execute the inner loop on grids defined on `x[1:7500, ]` and `y` that honor the user-specified "max block size" and respect the physical chunking. On that topic, last month I started to work on `multGrids()`, a version of `blockGrid()` specifically designed for defining "good grids" for block matrix multiplication. The idea is to use this for defining the inner grids. I'll do more work on this soon and will try to incorporate it to the parallel block matrix multiplication.

**Comment by LTLA** [comment]
Makes sense. It seems that there will be some large-scale changes to how the gridding will be done, so I'll hold off on making any changes to the code. The only thing I'll do is to coerce the output to a `DelayedArray` to preserve API consistency for the time being, so that downstream development can proceed.

The `multGrid` strategy is a sensible idea and helps divorce the concerns of parallel processing and memory management. I assume it will take advantage of `chunkGrid` to try to create jobs along chunk boundaries. However, the construction of the inner grid will require another choice about which multiplication strategy to use. This makes the overall cost calculations more challenging - I will have to think about this. 

I also realized that we have not considered the memory constraints of the output matrix. It is possible for two blocks to be small and yet yield a very large output matrix during block-wise processing, e.g.,:

```r
y <- runif(100)
x <- runif(100)
z <- x %*% t(y)
```

This would add yet another complication to the choice of the inner grid, if we wanted to ensure that the output is generated in chunks that fit inside a user-specified limit. I'm not particularly concerned by this eventuality but who knows.

**Comment by LTLA** [comment]
Having thought about this further, it is probably unnecessary for the initial cost calculation (for the choice of outer grid to define how the job is to be parallelized) to consider the costs of the inner grid (for memory management). Or to be more specific - it would be more accurate to consider it, but it complicates the code, adds overhead and is only helpful in situations where the block size limit is much lower than the chunk sizes.

So let's summarize our options. The one proposed by Herve probably looks like this:

1. Use `multGrid` to generate a number of outer grids for parallelization (like the ones that we already consider, i.e., by rows of `"x"`, by columns of `"y"` or by their `"common"` dimension).
2. Calculate the cost of each outer grid design, _assuming the block size limit is large enough to avoid redundant reads of the same chunks during the matrix multiplication in each worker_.
3. Choose the outer grid that minimizes the maximum cost across all workers.
4. For each worker, use `colGrid` or `rowGrid` to generate different inner grids as in **1**. We can't just reuse the scheme we chose the outer grid because we need to consider memory usage here.
5. Calculate the cost of each inner grid design, and choose the inner grid that minimizes the cost.

It is possible that an outer grid that is suboptimal under the assumption in **2** may actually be optimal when the assumption is violated in the choice of inner grid in **5**. We would not be able to detect this without computing all costs at once for all outer grid/inner grid combinations. But... well, that seems like a pain. 

The other option is a single grid approach, which is what we're currently doing. This would avoid the potential for suboptimality in the greedy choice of outer grid, as the block size limit and number of workers are considered at the same time. It also reduces the number of cost calculations as only one evaluation is performed. The only problem is that we can't control the in-memory size of the matrix product. For example:

- If a common dimension scheme was chosen, even the smallest possible blocks in a single-grid approach might yield a matrix product that exceeds the acceptable output size limit, as shown in the `z` example above.
- If we discarded schemes that exceed the acceptable output size, this would require us to switch to a grid choice that could potentially be much less cost-optimal.
- By comparison, an two-grid approach would be able to switch to a different scheme in the inner grid to respect the memory constraints, while still using the best outer grid.

One workaround is to make a "safe" version of `MULT` that switches to a block processing + save to sink approach when it detects that the size of the output object will be larger than the acceptable limit. This will probably be satisfactory for the few cases where the matrix product is much larger than its components. It effectively replicates a two-grid approach, with the difference that the second grid only rarely comes into play.

The single grid approach is simpler to understand and implement, probably has less overhead and avoids performance-compromising assumptions, but the outer/inner grid approach is more flexible and can more easily handle exotic data structures, e.g., `r/cbind`ed DAs from HDF5Matrices with different chunkdims.

**Comment by LTLA** [comment]
Another thought:

The cost-optimal scheme in most cases is to split each matrix by the common dimension (i.e., columns for the left argument, rows for the right argument), perform `%*%` for each chunk, and add the results back together. Unfortunately, the final product is dependent on the round-off error for the summation within each chunk. This leads to numerical differences to the results depending on the number of workers used. While the differences are minor, their presence violates what I would consider to be a basic promise of parallelization for non-random functions - to give **exactly** the same results regardless of whether I parallelize or not. As a developer, I don't mind some differences in downstream functions, but I do expect consistency in a core procedure like `%*%`.

So, I guess we should stick to breaking up only one of the input matrices to achieve the desired parallelization. This will guarantee the same numerical results regardless of the number of worker used. (Ignoring possible differences in precision between worker CPUs, which are beyond our control.) The plus side is that this makes the cost calculations a lot easier - we only have to decide which matrix to split, and it is now easy to dump parts of the result into the realization sink.

**Comment by hpages** [comment]
I'm on vacation right now and can't really elaborate but note that the promise of exact same result was broken a long time ago by basic summarization functions like `row`/`colMeans`. The issue is inherent to block-processing, not to parallelization per se:
```
library(DelayedArray)
set.seed(123)
m <- matrix(1e6 * runif(800 * 150), nrow=800)
res0 <- mean(m)
M <- DelayedArray(m)
res1 <- DelayedArray:::.BLOCK_mean(M, grid=blockGrid(M, block.length=150))
res1 - res0
# [1] -2.328306e-10
```
This is something that @PeteHaitch ran into a long time ago when working on DelayedMatrixStats. It will need to be discussed at some point somewhere in the documentation.

**Comment by LTLA** [comment]
Yes, I had thought of those implications as well. It's a bit disconcerting that the result becomes dependent on additional factors like the chunk size, but that's an argument to be had somewhere else.
