### ISSUE TITLE
Feature Request/Help on Applying Linear Models

### ISSUE THREAD

**Issue by avalcarcel9** [Bioconductor/DelayedArray#49]
Hello,

Absolutely amazing package! I am working on a relatively simply problem but can't quite figure out an efficient solution. I have a dataset x and a dataset y that I've saved as HDF5 objects and load them into R using `HDF5Array`. I want to run the linear models on each column of the y and x HDF5Array objects. Specifically, I want to run a set of linear models (`lm()`, `gee::gee()`, `lme4::lmer()`). Is there a way to use `blockApply()`, `apply()` or other delayed operations to do this efficiently? 

I've provided a simple example below for reference so you know exactly what I'm doing. This isn't how I've actually implemented but just wanted you to see exactly the problem.

```r
# Set made up data
x = as(matrix(1:40, ncol = 4), "HDF5Array")
y = as(matrix(41:80, ncol = 4), "HDF5Array")

# Initalize results
results = matrix(NA, ncol = 4)

for(i in 1:dim(x)[1]){
  # only use lm for simple example
  fit = lm(y[,1] ~ x[,1])
  results[i] = coefficients(fit)[2]
}
```

Is it possible to implement something like `lm()` and other modeling like the functions in `DelayedMatrixStats`?

**Comment by hpages** [comment]
The data in HDF5 files is often chunked and the chunks are compressed. So walking on a HDF5Matrix object and loading 1 row or 1 column at a time is generally inefficient because it leads to the same chunks being loaded in memory and uncompressed again and again.

For example, in this dataset:
```
x <- matrix(1:600000, ncol=600)
library(HDF5Array)
X <- writeHDF5Array(x, chunkdim=c(50, 30))
chunkdim(X)
# [1] 50 30
```
the chunks are rectangles of 50 x 30 matrix elements. So each row or column crosses 20 chunks. This means that when you request a single row (or column) the low-level code in the HDF5 library actually loads 50 rows (or 30 columns). And because the library doesn't cache the data, 50 rows (or 30 columns) are loaded again when you request the next row (or column).

This is why doing something like:
```
lapply(seq_len(ncol(X)), function(j) foo(X[ , j]))
```
can be VERY inefficient.

A more efficient strategy is to process the object by blocks of columns and to choose blocks that cover full chunks. If you need to walk on the columns of 2 matrix-like objects, then you can use the following function:
```
### Walk on the columns of 2 matrix-like objects 'X' and 'Y' and apply binary
### function 'FUN' to them. 'X' and 'Y' must have the same number of columns.
### Return a list with one list element per column in 'X' (or in 'Y').
### So is semantically equivalent to:
###   lapply(seq_len(ncol(X)), function(j) FUN(X[ , j], Y[ , j]))
### **except** that colApply2() uses block processing (with blocks made of 'by'
### columns) so will in general be much more efficient.
colApply2 <- function(X, Y, FUN, by=NULL)
{
    FUN <- match.fun(FUN)
    X_dim <- dim(X)
    Y_dim <- dim(Y)
    stopifnot(length(X_dim) == 2L,
              length(Y_dim) == 2L,
              X_dim[[2L]] == Y_dim[[2L]])
    X_grid <- colGrid(X, ncol=by)
    Y_grid <- colGrid(Y, ncol=ncol(X_grid[[1L]]))
    ## The blocks in 'X_grid' and 'Y_grid' are made of full columns and the
    ## 2 grids have the same number of blocks and their blocks have the same
    ## number of columns.
    nblock <- length(X_grid)  # should be the same as 'length(Y_grid)'
    unlist(
        lapply(seq_len(nblock),
            function(b) {
                X_block <- read_block(X, X_grid[[b]])
                Y_block <- read_block(Y, Y_grid[[b]])
                ## Just for sanity but this should never happen.
                stopifnot(ncol(X_block) == ncol(Y_block))
                lapply(seq_len(ncol(X_block)),
                       function(j) FUN(X_block[ , j], Y_block[ , j]))
            }),
        recursive=FALSE)
}
```
Then:
```
y <- matrix(600001:1200000 + runif(600000), ncol=600)
Y <- writeHDF5Array(y, chunkdim=c(50, 30))  # using the same chunk geometry as for X
chunkdim(Y) 
# [1] 50 30

FUN <- function(x, y) coefficients(lm(x ~ y))[[2L]]

system.time(res1 <- lapply(seq_len(ncol(X)), function(j) FUN(X[ , j], Y[ , j])))
#    user  system elapsed 
#    4.55    0.04    4.59 

system.time(res2 <- colApply2(X, Y, FUN, by=30))
#    user  system elapsed 
#   0.530   0.004   0.534 

identical(res1, res2)
# [1] TRUE
```

Hope this helps,
H.

**Comment by avalcarcel9** [comment]
This is exactly what I needed! Thank you so much Herve! Does this work as a function in any packages in your ecosystem? I'm happy to fork, add a few checks, and then submit a PR for you if you know which package it would be a good fit in. If not I'll likely edit slightly to add checks and put it in a personal package for myself if thats alright with you?

FYI @muschellij2

**Comment by hpages** [comment]
I'm still trying to figure out what set of `*apply()` functions I want to have in DelayedArray. This one is probably a little bit too specialized to be a good candidate, at least for now. You see, I don't want to add it now, then change my mind later, which will mean going thru the hassle of a deprecate/defunct cycle, fix a bunch of packages around that are already using the function, and deal with complaints from the unhappy users whose code I didn't fix.

So for now, I'd say put `colApply2()` in your package.

H.

**Comment by avalcarcel9** [comment]
Not a problem at all! One last questions. Can `by` be larger than `chunkdim(x)` or `chunkdim(y)`? I tested out cases today and it runs but I wasn't sure if there were memory/efficiency or data problems in doing this. On a few test cases it ran fast with no memory problems but I figured I'd ask before closing this issue.

**Comment by hpages** [comment]
`by` can be any number between 1 and the nb of columns in the matrices. However, for the block processing mechanism to be efficient, blocks should always cover _full_ chunks. This is why I set it to 30 in my example because that's the chunk width. This means that blocks of 1000 x 30 were used, that blocks made of 20 _full_ chunks. Note that I could have set it to any multiple of 30 and that would have just made the blocks bigger i.e. more chunks per block but still _full_ chunks.

If you set `by` to a number that is not a multiple of the chunk width, things still work (i.e. you'll get the right answer) but block processing will not be optimal because some chunks will be loaded and uncompressed twice in memory.

**Comment by avalcarcel9** [comment]
Great explanation. Makes perfect sense now! Thanks so much for the help on this! My code is unbelievably faster now!
