### ISSUE TITLE
Transposing a subsetted DelayedArray: turtles all the way down?

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/DelayedArray#5]
I recently noticed an interesting behaviour with transposing a subsetting DelayedArray:

```r
library(DelayedArray)
blah <- matrix(runif(1000), ncol=20, nrow=50)
X <- DelayedArray(blah)
Y <- t(X[,20:1])
```

When I try to dig out the seed, I need to go pretty deep:

```r
class(Y)[1]
## [1] "DelayedMatrix"
class(Y@seed)[1]
## [1] "SeedDimPicker"
class(Y@seed@seed)[1]
## [1] "DelayedMatrix"
class(Y@seed@seed@seed)
## [1] "matrix"
```

This gets even more amusing if I transpose and subset again:

```r
Z <- t(Y[20:1,])
```

... which results in the following:

```r
class(Z)[1]
## [1] "DelayedMatrix"
class(Z@seed)[1]
## [1] "SeedDimPicker"
class(Z@seed@seed)[1]
## [1] "DelayedMatrix"
class(Z@seed@seed@seed)[1]
## [1] "SeedDimPicker"
class(Z@seed@seed@seed@seed)[1]
## [1] "DelayedMatrix"
class(Z@seed@seed@seed@seed@seed)
## [1] "matrix"
```

You could say that I shouldn't be trying to dig out the seed in the first place, and that's fair enough. However, I can imagine that at least a few of us will be writing back-end specific code for greater efficiency (_beachmat_ for me, and probably also _DelayedMatrixStats_ for @PeteHaitch), in which case it would be pretty inconvenient to have to dig so deep to figure out what the backend actually is. Not only that - we would have to correct for multiple sets of delayed operations, not just in `Y` but also in `Y@seed@seed`, which makes life more difficult when doing back-end specific optimizations.

From the outside looking in, it should be possible for (i) the first transposition to store the actual backend (in this case, `"matrix"`) as the `seed` of the `SeedDimPicker`, rather than storing a `DelayedMatrix`; and (ii) for re-transpositions to undo the construction of a `SeedDimPicker` so that `Z@seed` becomes identical to `X@seed` (aside from relatively minor modifications to `index`). This seems simpler, and possibly more efficient, unless there are some compelling arguments for the current set-up. 

FYI, _beachmat_ now does chunk-by-chunk realization when it encounters an unknown seed type, so the nested seed setup above will work happily with _beachmat_. However, certain optimizations that skip explicit realization are no longer possible with the nested seeds.

Oh, and:

```
R Under development (unstable) (2017-10-27 r73632)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /home/cri.camres.org/lun01/Software/R/trunk/lib/libRblas.so
LAPACK: /home/cri.camres.org/lun01/Software/R/trunk/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] DelayedArray_0.5.22 BiocParallel_1.13.1 IRanges_2.13.28    
[4] S4Vectors_0.17.37   BiocGenerics_0.25.3 matrixStats_0.53.1 

loaded via a namespace (and not attached):
[1] compiler_3.5.0
```

**Comment by hpages** [comment]
Hi Aaron,

I'm going to make some important changes over the next couple of days to the internals of DelayedArray objects. They will make it easier to address this issue.

H.

**Comment by hpages** [comment]
Hi Aaron,

This is "addressed" in DelayedArray 0.5.24. With this version the delayed operations are still stacking up inside the object (they are actually represented as a tree, there is some very brief information about this in `?DelayedOp`). However the `seed()` accessor now reaches the "original" seed instead of the depth-1 seed:
```
library(DelayedArray)
blah <- matrix(runif(1000), ncol=20, nrow=50)
X <- DelayedArray(blah)
Y <- t(X[,20:1])
Z <- t(Y[20:1,])
class(seed(Z))
# [1] "matrix"
```
Unlike with DelayedArray < 0.5.24, the internal tree of delayed ops now stores all the operations that were applied by the user, even if they are no-ops (e.g. `A <- A[ , , ]` or `dimnames(A) <- dimnames(A)`). Also consecutive operations of the same type are not squashed anymore. So the tree reflects the  history of the object. One item in the TODO list is to provide a user-friendly visualization of the tree.

This could change in the future (maybe a global option could control whether the tree should be simplified as we go or not).

Hope this works for you,
H.

**Comment by LTLA** [comment]
Okay. From _beachmat_'s perspective, it would be nice to also have some R functions for parsing aspects of this tree. I'm thinking of three functions that would make my life easier:

- One function that tells me if the final matrix is "net transposed" (i.e., when "adding up" all the transposition operations) relative to the original seed.
- One function that tells me the "net subsetting" (when adding up all the subsetting operations).
- One function that tells me if there were any operations other than transposition or subsetting (or dimname setting), i.e., whether or not the _contents_ of the matrix have changed.

These would enable data access to be optimized in _beachmat_ and other APIs. If matrix contents do not change, we only have to extract the seed and do look-ups according to the net subsetting and transposition.

**Comment by hpages** [comment]
I see. I'll try to come up with something for that. In the mean time I just added `showtree()` for visualizing the tree of delayed operations stored in the DelayedArray object. It's in DelayedArray 0.5.24 (no version nump yet). See `?showtree`

**Comment by LTLA** [comment]
While I'm in request mode, I might as well make one more. 

Is it possible to have a function like `seed()` that returns a matrix-like representation, even for `HDF5ArraySeed` objects? As in, if I call this function on a `DelayedMatrix` constructed from a `HDF5Matrix`, I would get a `HDF5Matrix` back (i.e., as if the delayed operations had not happened). This would make _beachmat_'s life a bit easier; when I encounter a `DelayedMatrix`, I would do the following:

1. Call the three R functions that tell me if the object has any non-transpose/subset delayed ops.
2. If there are no such ops in (1), call the `seed`-like R function that gives me back the op-free matrix.
3. Enter the op-free matrix into the _beachmat_ API, with a wrapper that handles transpose/subset.
4. If there are ops in (1), handle data access from the matrix with a chunked realization strategy.

This would also be more future-proof as I won't have to dig around the `DelayedArray` slots anymore.

**P.S.** _beachmat_'s builds just failed because of the loss of the `delayed_ops` field. For the time being, I've switched all instances of the `DelayedMatrix` input to a chunked realization approach.

**Comment by hpages** [comment]
Hi Aaron,

How about doing `DelayedArray(seed(x))` to "reset" the object? (IIUC what your last request is about).

About the three functions you proposed earlier:
I added `netSubsetAndAperm()` to DelayedArray 0.5.30. It combines your first 2 functions in 1. If `x` is a DelayedMatrix object with a **single** 2-dimensional seed, `netSubsetAndAperm(x)` will return a list of 2 subscripts, one along each dimension **of the seed**, that describes the _net subsetting_.  In addition, if `x` is transposed with respect to its seed, the list will have a `dimmap` attribute on it. Note that in the very particular case where `dim(x)` and `dim(seed(x))` are both equal to 2, the `dimmap` attribute, when present, can only by `2:1`. See `?netSubsetAndAperm` for the details.

I'm going to add something that inspects the tree of delayed ops and tells you whether it contains ops that alter the original values of the array elements or not. This is your 3rd function. Should be the easy one.

H.

**Comment by LTLA** [comment]
Sweet, thanks Herve. I'll check these out when I'm back on Thursday.

**Comment by hpages** [comment]
Done: https://github.com/Bioconductor/DelayedArray/commit/baf8b8cfedee894b40a38d54a05e46e76b0a75bf

**Comment by LTLA** [comment]
I've had a play with these functions, and they seem to do as desired; thanks.

The only remaining issue is that `DelayedArray(seed(x))` does not entirely do what I want. For `HDF5ArraySeed` and `RleArraySeed` objects, it's fine; but for the other matrix representations, it unnecessarily wraps them in a `DelayedMatrix` container, which complicates the determination of the back-end at the C++ level. To achieve the desired behaviour, I do something ugly:

```r
mat <- seed(mat)
if (is(mat, "HDF5ArraySeed") || is(mat, "RleArraySeed")) { 
     # Note, not sure how many classes there are.
     mat <- DelayedArray(mat)
}
```

I don't suppose you have a more elegant solution? Perhaps an `as.matrix=TRUE` option in `seed`, which guarantees the return of a matrix-like object (i.e., returns the raw seed if the seed is already matrix-like, otherwise returning a `DelayedArray()`-wrapped seed)?

**Comment by hpages** [comment]
Hi Aaron,

I'm not sure I understand what you are after. I'm just going to throw a few random comments to try to clarify things:
- `seed(x)` **always** returns an array-like object. By array-like I mean an object for which `dim()` is not NULL.
- When you say that you'd like a function like `seed()` that returns a matrix-like representation, even for HDF5ArraySeed objects, are you saying that you'd like `seed()` to work on an HDF5ArraySeed object? Then it would be a no-op right? If that's what you need, you could just do `if (is(x, "DelayedArray")) seed(x) else x`. If what you are saying instead is that you'd like `seed(x)` to return the seed in a matrix-like form, even when the seed is an HDF5ArraySeed object, then that's where you get me confused. An HDF5ArraySeed object **is** an array-like object (or matrix-like object if `length(dim()) == 2`).
- Or maybe you are saying that you'd like a function like `seed()` that returns an **ordinary** array or matrix (the fact that you suggest to add the `as.matrix` option to the `seed()` function makes me think that maybe this is what you are after). If that's the case, just do `as.array(DelayedArray(seed(x)))`. Yes, that is triggering a lot of unnecessary work if `seed(x)` is already an ordinary array. So avoid it with:
    ```
    seed_as_array <- function(x)
    {
        x_seed <- seed(x)
        if (is.array(x_seed))
            return(x_seed)
        as.array(DelayedArray(x_seed))
    }
    ```
    Note that like `seed(x)`, `seed_as_array(x)` will fail if `x` has multiple seeds.

Am I getting closer?
H.

**Comment by hpages** [comment]
The seed can be anything that complies with the "seed contract" i.e. that supports `dim()`, `dimnames()` and `extract_array()`. That's all what DelayedArray cares about. Some seeds will indeed support `[` and other won't but this is not DelayedArray's business. IIUC you want to wrap the seed in a DelayedArray only if it doesn't support `[`. But how about using `extract_array()` instead of `[`? Then you wouldn't need this wrapping at all. `seed(x)` is guaranteed to support `extract_array()`. Some important differences between `extract_array()` and `[`:
1. `extract_array()` always returns an ordinary array so is not an endomorphism.
2. `extract_array()` takes only 2 arguments `x` and `index`. The 2nd argument `index` must be a list of integer vectors. 
3.  `extract_array()` never drops dimensions.
4.  It never triggers block-by-block realization.
See `?extract_array` for more information.
Let me know if using `extract_array()` is not an option for you.

**Comment by LTLA** [comment]
Probably not, unfortunately; inflation to an ordinary array would not be good in most cases. The main problem is that I'm trying to squeeze out as much performance as possible, and thus trying to get the "native" format of the seed matrix; but at some point, it gets "too native" and I just end up with a Seed class that I can't do much with. 

I could probably check `hasMethod` to see if there is a subsetting method - if so, it's a full matrix object that can directly enter the _beachmat_ API, if not, it's a seed that needs to be wrapped in a `DelayedArray()`. Do you think this would work?

**Comment by PeteHaitch** [comment]
I've ended up with a somewhat clunky `hasMethod()`-based solution for the same/similar issue in **DelayedMatrixStats**. But I want to revisit this in the next development cycle.

**Comment by hpages** [comment]
I was going to suggest `hasMethod` as the next thing to consider. I have no experience with it. It doesn't seem to be a reliable solution though:
```
> hasMethod(`[`, "HDF5ArraySeed")
[1] TRUE
```
This is not a bug. HDF5ArraySeed objects actually inherit the default `"["` method which is the `[` primitive function defined in base R:
```
 > selectMethod("[", "ANY")
.Primitive("[")
```
The `[` primitive function will raise an error:
```
> HDF5ArraySeed(tally_file, "/ExampleStudy/16/Coverages")[3, 5, 2]
Error in HDF5ArraySeed(tally_file, "/ExampleStudy/16/Coverages")[3, 5,  : 
  object of type 'S4' is not subsettable
```
Note that the error is different when there is no method defined for a given object:
```
> seqnames(HDF5ArraySeed(tally_file, "/ExampleStudy/16/Coverages"))
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqnames’ for signature ‘"HDF5ArraySeed"’
```
The fundamental problem here is that not just because there is a `"foo"` method for A objects means that A objects support `foo()`. It seems that your problem boils down to that i.e. to reliably detect whether a given object supports `[`. That could be a good question for bioc-devel or SO. My ugly attempt at tackling this is with something like this:

1. Call hasMethod(). If it returns FALSE then `x` does not support subsetting. If it returns TRUE, keep going.
2. Try to subset i.e. subset in a `try()` statement. If you get an error, ASSUMING YOUR SUBSCRIPTS ARE VALID, then `x` does not support subsetting. If it doesn't error, keep going.
3. Do some sanity checks on the objects returned in (2) e.g. does it have the expected dimensions and type?

Ugly and hacky. Generally speaking using a `try()`-based approach to detect capabilities is not good as it can hide unintended errors. Hopefully there is a better way.

My last proposal: there is no clear concept of "seed-only class". However, things like RleArraySeed, HDF5ArraySeed, GDSArraySeed, etc... are **normally** associated with a DelayedArray extension: RleArray, HDF5Array, GDSArray. When you call `DelayedArray()` on a seed, you get an object of the class associated with the seed class. If the seed is an ordinary matrix or array, or a SparseMatrix object, or a DataFrame object, there is no DelayedArray extension associated with it i.e. calling `DelayedArray()` on it returns a DelayedArray **instance**. Maybe you could use that to detect that the seed belongs to a "seed-only class" (whatever that means)? Note that `class(DelayedArray(seed(x))) == "DelayedArray"` is not equivalent to "`seed(x)` is subsettable". You could imagine that `DelayedArray()` works on some obscure Matrix subclass that doesn't support `[` or that the author of a seed class like GDSArraySeed decided to implement a `"["` method for those objects.

**Comment by LTLA** [comment]
Your second suggestion might be worth a shot... so in other words, "pristine-ify" the `DelayedArray` and see if its class is no longer exactly an `DelayedArray`. Yes, this sounds like what I wanted.

**Comment by hpages** [comment]
Sounds good. Glad we are making progress. I want to emphasize the fact that authors of a DelayedArray backend (e.g. GDSArraySeed) are strongly encouraged to define a DelayedArray extension (e.g. GDSArray) but this is not enforced (I can't think of an easy way to enforce this). See https://github.com/Bioconductor/DelayedArray/blob/master/vignettes/02-Implementing_a_backend.Rmd#implementing-high-level-classes-adsarray-and-adsmatrix
So for example if Qian had decided to not define the GDSArray class in the GDSArray package, calling `DelayedArray()` on a GDSArraySeed object would return a DelayedArray **instance**. AFAICT all the DelayedArray backends that I'm aware of also have the associated high-level class defined so you should be good.

**Comment by LTLA** [comment]
The second suggestion seems to have worked properly, thanks.

**Comment by hpages** [comment]
Excellent!
